version: "3.7"

services:
  nginx:
    image: "nginx:mainline"
    depends_on:
      - kratos
      - web
    ports:
      - 4455:4455
      - 4456:4456
    restart: on-failure
    depends_on: 
      - web
      - bus-api
      - kratos
    networks:
      - intranet
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  kratos:
    extends:
      file: ./packages/kratos/docker-compose.yml
      service: kratos

  bus-api:
    extends:
      file: ./packages/bus-api/docker-compose.yml
      service: bus-api

  web:
    extends:
      file: ./packages/web/docker-compose.yml
      service: web

networks:
  intranet:

volumes:
  kratos:
