version: "3.7"

services:
  kratos-migrate:
    image: oryd/kratos:v0.7.1-alpha.1-sqlite
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
    volumes:
      - type: volume
        source: kratos
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/.kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    image: oryd/kratos:v0.7.1-alpha.1-sqlite
    ports:
      - "4433:4433" # public
      - "4434:4434" # admin
    restart: unless-stopped
    environment:
      - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
    command: serve -c /etc/config/kratos/.kratos.yml --dev
    volumes:
      - type: volume
        source: kratos
        target: /var/lib/sqlite
        read_only: false
      - type: bind
        source: ./.kratos
        target: /etc/config/kratos
    networks:
      - intranet

networks:
  intranet:

volumes:
  kratos-sqlite:
