version: "3.7"

services:
  bus-api:
    image: "node:lts-alpine"
    user: "node:node"
    working_dir: "/bus-api"
    command: ["yarn", "dev"]
    stdin_open: true
    environment:
      - MONGO_DB=mongodb://host.docker.internal:27017/ride
    networks:
      - intranet
    restart: on-failure
    volumes:
      - "./:/bus-api:cached"
    ports:
      - "3000:3000"

networks:
  intranet:
